---
abstract: 'Provide logging via Log::Any'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Log::Any::Test: '0'
  Moo: '0'
  Test::FailWarnings: '0'
  Test::More: '0.96'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-Role-Logger
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  MooX::Role::Logger:
    file: lib/MooX/Role/Logger.pm
    version: '0.005'
  MooseX::Role::Logger:
    file: lib/MooseX/Role/Logger.pm
    version: '0.005'
requires:
  Log::Any: '0'
  Moo::Role: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/MooX-Role-Logger/issues
  homepage: https://github.com/dagolden/MooX-Role-Logger
  repository: https://github.com/dagolden/MooX-Role-Logger.git
version: '0.005'
x_authority: cpan:DAGOLDEN
